import { z } from 'zod';

export const customerSchema = z.object({
  addresses: z.array(z.unknown()),
  authenticationMode: z.unknown(),
  billingAddressIds: z.array(z.string()).optional(),
  companyName: z.string().optional(),
  createdAt: z.string(),
  customerGroup: z.unknown(),
  customerNumber: z.string().optional(),
  dateOfBirth: z.string().optional(),
  defaultBillingAddressId: z.string().optional(),
  defaultShippingAdressId: z.string().optional(),
  email: z.string(),
  extarnalId: z.string().optional(),
  firstName: z.string().optional(),
  id: z.string(),
  isEmailVerified: z.boolean(),
  key: z.string().optional(),
  lastModifiedAt: z.string(),
  lastName: z.string().optional(),
  locale: z.string().optional(),
  middleName: z.string().optional(),
  password: z.string().optional(),
  salutation: z.string().optional(),
  shippingAddressIds: z.array(z.string()).optional(),
  stores: z.unknown(),
  title: z.string().optional(),
  vatId: z.string().optional(),
  version: z.number(),
});
